### ISSUE TITLE
Entering fullscreen on Windows doesn't call oc_on_resize

### ISSUE THREAD

**Issue by martinfouilleul** [orca-app/orca#11]
_Imported from gitea. See https://git.handmade.network/hmn/orca/issues/125 for previous conversation_

Reported by bobbytronics on discord: https://discord.com/channels/239737791225790464/1121811864066732082/1153058137436340354

> I was trying out the clock example and wanted to fullscreen in Windows 11 and noticed that oc_on_resize does not get called.

**Comment by rdunnington** [comment]
Turns out this issue wasn't unique to Windows 11, we just weren't properly handling resize/restore events. Fixed by #44
