### ISSUE TITLE
Separate dev tooling and user tooling

### ISSUE THREAD

**Issue by bvisness** [orca-app/orca#22]
The current tooling is designed to support both normal user needs and core developer needs. The same `orca` "executable" bundles apps and builds the runtime itself. This seemed nice but seems to have led to unneeded confusion - and makes it difficult to separate the technical requirements of normal users and core developers.

The "user tooling" (`orca bundle` for example) will be rewritten in C. Since we plan to distribute premade builds of the tool (issue TBD), this removes all system environment dependencies for the user tooling.

For now, the dev tooling (everything under `orca dev`, bindings generation, etc.) will remain in Python. This may change in the future, but for now we will be making lots of rapid changes and don't want to slow ourselves down. Installing a sufficiently new version of Python seems like a reasonable expectation if you intend to work directly on the runtime.

**Comment by bvisness** [comment]
Notes for myself while I work:

- [ ] Figure out rough new "install" process for both tooling and runtime. Needs to handle:
  - `orca bundle` - runtime executable / libraries / debug info, fonts
  - `orca sdk` - C source
  - Multiple versions, with room for integrity checks (checksums)
- [ ] Manually place files in system directories for bundle
- [ ] Rewrite bundle script in C
- [ ] Rewrite C compilation helper
  - This should be substantially different from the existing documentation-style command,
    and should instead rely on versions of Orca in the system install directory. `orca sdk` instead of `orca cflags`.

**Comment by martinfouilleul** [comment]
closed by #55
