### ISSUE TITLE
Build a better workflow around the system install directory

### ISSUE THREAD

**Issue by bvisness** [orca-app/orca#23]
The only current way to work with Orca outside of the Orca source is to vendor it - but the vendor workflow has lots of problems. After further discussion with @martinfouilleul, we don't intend to fix those issues and instead want to build a good non-vendor workflow for now.

The basic idea is to depend on the system Orca install. The main challenges are to handle tool versioning (making sure you are always building with an acceptable version of the runtime) and including the Orca sources (for things like UI). We should be able to use some kind of project-root file like a `package.json` or `go.mod` to solve the tooling issue. The source issue can be taken care of with a CLI command that prints the path to the user's system install.

**Comment by ilidemi** [comment]
> The source issue can be taken care of with a CLI command that prints the path to the user's system install.

Just an idea, `orca create-app MyApp` could copy the libraries and build script(s) into the current directory

**Comment by martinfouilleul** [comment]
Closed by #55. The tool can be passed a `--version` flag when bundling or printing the sdk directory.
