### ISSUE TITLE
Create doc site

### ISSUE THREAD

**Issue by bvisness** [orca-app/orca#70]
We need a site for docs. We'd rather have a dedicated site rather than ask people to navigate GitHub wikis or info in the source tree.

In our Orca meeting today we discussed the possibility of just setting up a simple GitHub pages workflow with some static site generator. I think that's a good idea to get us going. We can create a separate repo and then just set it up at docs.orca-app.dev.

**Comment by martinfouilleul** [comment]
I created a new repo for the doc site using mkdoc: http://github.com/orca-app/orca-doc
The site is accessible at https://docs.orca-app.dev

**Comment by martinfouilleul** [comment]
Let's keep track of this in #73
