### ISSUE TITLE
Max flow rate doesn't respect the initial flow value

### ISSUE THREAD

**Issue by otede** [orca-app/orca#74]
... entered in the initial popup. It always starts from 0. So when I choose from 20 to 40 I get a "tower" twice as high as 0-20 tower instead of the same height.
![irfan_20240616_122133](https://github.com/orca-app/orca/assets/5107909/d79301d6-32a2-4bf6-81ed-cc16fcfbec4a)

**Comment by bvisness** [comment]
Is this some new sample project I'm unaware of, or was this issue submitted to the wrong GitHub project? 😄

**Comment by otede** [comment]
> Is this some new Orca sample project I'm unaware of, or was this issue submitted to the wrong GitHub project? 😄
![irfan_20240616_192824](https://github.com/orca-app/orca/assets/5107909/69aa6d93-fcd7-4e48-8f77-fc0cabb8c25f)

**Comment by otede** [comment]
Ah, I see. Orca =/= Orca Slicer :) I don't even know what wasm is :D
